//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.239
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NTreva.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NTreva.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The {CONFIGDIR} which holds a package.config file..
        /// </summary>
        internal static string CommandLine_Param_ConfigDir_Description {
            get {
                return ResourceManager.GetString("CommandLine_Param_ConfigDir_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to c=|configdir=.
        /// </summary>
        internal static string CommandLine_Param_ConfigDir_Key {
            get {
                return ResourceManager.GetString("CommandLine_Param_ConfigDir_Key", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show this message and exit..
        /// </summary>
        internal static string CommandLine_Param_Help_Description {
            get {
                return ResourceManager.GetString("CommandLine_Param_Help_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to h|help.
        /// </summary>
        internal static string CommandLine_Param_Help_Key {
            get {
                return ResourceManager.GetString("CommandLine_Param_Help_Key", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The full path to the {OUTPUT} file..
        /// </summary>
        internal static string CommandLine_Param_Output_Description {
            get {
                return ResourceManager.GetString("CommandLine_Param_Output_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to o=|output=.
        /// </summary>
        internal static string CommandLine_Param_Output_Key {
            get {
                return ResourceManager.GetString("CommandLine_Param_Output_Key", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The directory that contains the unpacked packages..
        /// </summary>
        internal static string CommandLine_Param_PackageDir_Description {
            get {
                return ResourceManager.GetString("CommandLine_Param_PackageDir_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to p=|packagedir=.
        /// </summary>
        internal static string CommandLine_Param_PackageDir_Key {
            get {
                return ResourceManager.GetString("CommandLine_Param_PackageDir_Key", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified template could not be loaded from the resource stream..
        /// </summary>
        internal static string Exceptions_Messages_CouldNotLoadTemplate {
            get {
                return ResourceManager.GetString("Exceptions_Messages_CouldNotLoadTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The provided package ID is not valid..
        /// </summary>
        internal static string Exceptions_Messages_InvalidPackageId {
            get {
                return ResourceManager.GetString("Exceptions_Messages_InvalidPackageId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://www.google.com/search?q={0}.
        /// </summary>
        internal static string GoogleSearchQuery {
            get {
                return ResourceManager.GetString("GoogleSearchQuery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to nTreva (version: {0}).
        /// </summary>
        internal static string Header_ApplicationAndVersion {
            get {
                return ResourceManager.GetString("Header_ApplicationAndVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to     {0} (version: {1}). For more information see: {2}.
        /// </summary>
        internal static string Header_OtherPackages_IdAndLicense {
            get {
                return ResourceManager.GetString("Header_OtherPackages_IdAndLicense", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This application includes the following open source software:.
        /// </summary>
        internal static string Header_OtherPackages_Intro {
            get {
                return ResourceManager.GetString("Header_OtherPackages_Intro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usage: ntreva.exe [OPTIONS].
        /// </summary>
        internal static string Help_Usage_Intro {
            get {
                return ResourceManager.GetString("Help_Usage_Intro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finished processing packages. Wrote information to: {0}.
        /// </summary>
        internal static string Output_Completed {
            get {
                return ResourceManager.GetString("Output_Completed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ERROR: Incorrect commandline arguments provided. Try using the --help argument for more information..
        /// </summary>
        internal static string Output_Error_InvalidInput {
            get {
                return ResourceManager.GetString("Output_Error_InvalidInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ERROR: No value provided for all parameters..
        /// </summary>
        internal static string Output_Error_MissingValues {
            get {
                return ResourceManager.GetString("Output_Error_MissingValues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Processing: {0} ....
        /// </summary>
        internal static string Output_ProcessingPackage {
            get {
                return ResourceManager.GetString("Output_ProcessingPackage", resourceCulture);
            }
        }
    }
}
